image_width: 1600
image_height: 1200
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [828.38219,   0.     , 832.40365,
           0.     , 833.564  , 593.66211,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.287181, 0.068984, -0.002557, 0.000203, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [578.85095,   0.     , 832.04684,   0.     ,
           0.     , 584.02698, 584.28667,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
