image_width: 1600
image_height: 1200
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [843.21779,   0.     , 748.70998,
           0.     , 847.4891 , 592.95566,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.270111, 0.050767, -0.000137, 0.003668, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [540.54639,   0.     , 769.86321,   0.     ,
           0.     , 543.54578, 591.10226,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
