image_width: 1600
image_height: 1200
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [836.77298,   0.     , 860.32147,
           0.     , 839.75836, 550.65433,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.271306, 0.055006, -0.000610, -0.000719, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [556.44495,   0.     , 855.87375,   0.     ,
           0.     , 558.88019, 547.09838,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
